### ISSUE TITLE
networkx-2.3 pin breaking macOS builds on python3.9

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/staged-recipes#14734]
@conda-forge/staged-recipes, I'm sure someone else has already reported this, but it looks like the osx miniforge installation has just jumped to python3.9, which breaks `networkx` so even `skip: true  # [osx]` builds are breaking [[ref]](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=308965&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310):

```pytb
+ python .ci_support/build_all.py

Traceback (most recent call last):
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 2, in <module>
    import networkx as nx
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/Users/runner/miniforge3/lib/python3.9/fractions.py)
```

This was corrected in https://github.com/networkx/networkx/pull/3639 and released with `networkx-2.4`.

_Originally posted by @duncanmmacleod in https://github.com/conda-forge/staged-recipes/issues/14227#issuecomment-826674984_

**Comment by maresb** [comment]
Just started discussing this myself on [Gitter](https://github.com/conda-forge/staged-recipes/issues/14734)

**Comment by duncanmmacleod** [comment]
I think the pin was introduced in https://github.com/conda-forge/staged-recipes/pull/12438 by @isuruf, but there isn't anything obvious to explain _why_ that pin is required.

**Comment by maresb** [comment]
@chrisburr via Gitter:

> Miniforge was just updated to Python 3.9

**Comment by maresb** [comment]
I deleted all the `networkx=2.3` pins [here](https://github.com/conda-forge/staged-recipes/pull/14732/files). Unfortunately that just caused `networkx` to not be installed.

Sadly I don't have any time to work on this today. Sorry I can't be of any more help.

**Comment by chrisburr** [comment]
It looks like there are source incompatibilities with the new version: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=309003&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823

I don't have time to look further at the moment but I guess we need to either:
* Workaround the issue by using a Python 3.8 based version of miniforge
* Adapt for the code to support the newer networkx releases

**Comment by runette** [comment]
There is a deprecation in networkx 2.4 that is causing the second problem - see the change notes here https://networkx.org/documentation/stable/release/release_2.4.html

" G.node –> use G.nodes"

so - I changed the networkx pins to explicit 2.4 - in this commit https://github.com/conda-forge/staged-recipes/pull/14544/commits/22aabce24a2eb8d03f32a84773b5ca2846e0fc6f

I change `.node` to `.nodes` in `compute_build_graph.py`  this commit  https://github.com/conda-forge/staged-recipes/pull/14544/commits/da35ac18c5e6b1a3a6770699503cc859db4b6165

I also had to change `.node` to `.nodes` in `build_all.py` in this commit https://github.com/conda-forge/staged-recipes/pull/14544/commits/ad34b2f90a386cfb7df1127ee80a52f0a9bb85e0

It looks like it has worked

**Comment by runette** [comment]
this should be closed by https://github.com/conda-forge/staged-recipes/pull/14736

**Comment by chrisburr** [comment]
It works, thanks again!
