### PR TITLE
ENH: Adding eon

### PR DESCRIPTION
**Pull request by HaoZeke**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by HaoZeke** [comment]
As the contributor and current maintainer I agree to be listed.

**Comment by HaoZeke** [comment]
@conda-forge/help-c-cpp

**Comment by HaoZeke** [comment]
Kinda stumped by the error, since the `variant` should cover this:

```bash
In file included from ../client/Parameters.cpp:11:
 │ │ ../client/NudgedElasticBand.h:98:49: error: 'path' is unavailable: introduced in macOS 10.15 unknown - see https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
 │ │    98 | filePathInit(const std::vector<std::filesystem::path> &fsrcs,
 │ │       |                                                 ^
 │ │ $PREFIX/bin/../include/c++/v1/__filesystem/path.h:381:33: note: 'path' has been explicitly marked unavailable here
 │ │   381 | class _LIBCPP_EXPORTED_FROM_ABI path {
 │ │       |                                 ^
```


Needed `-D_LIBCPP_DISABLE_AVAILABILITY`

**Comment by HaoZeke** [comment]
@conda-forge/help-c-cpp, ready for review!

File: recipes/eon/recipe.yaml [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+  build_num: 0
+  git_rev: 18af56a6646ef561a71b322c7d9c98e134696558
+
+package:
+  name: eon
+  version: ${{ version }}
+
+source:
+  url: https://github.com/TheochemUI/eOn/archive/${{ git_rev }}.tar.gz
+  sha256: 1ad24b4a99c6d9c27b675ed6922fe18c8e855dca56f5e0b3e623ac53d6153e4b
```
Comment (danielnachun) [inline recipes/eon/recipe.yaml]: Unfortunately we cannot accept packages into conda-forge that don't use stable tagged releases.  I see that the upstream repository does have some tags but they do not obey standard semantic versioning, and don't match the version you've specified.  Please work with the upstream to get a `3.0.0` tag, and please keep in mind that future version updates must also be tagged releases that follow semantic version, not git commits or the non-standard tags currently being used.  If a package does not follow semantic versioning it becomes almost impossible to determine the version being used, and given the importance of versioning for reproducibility, we require packages to follow the industry standards for package versioning.

Comment (HaoZeke) [reply recipes/eon/recipe.yaml]: Thanks @danielnachun, it took a while but we were able to cut an upstream release. Looking forward to having EON in conda-forge :)

**Comment by HaoZeke** [comment]
@conda-forge/help-c-cpp, ready for review!

File: recipes/eon/build.nu [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+        install_name_tool -delete_rpath $rpath $eonclient_path
+    }
+
+    # Add a single, correct rpath
+    print "INFO: Adding correct rpath: @loader_path/../lib"
+    install_name_tool -add_rpath "@loader_path/../lib" $eonclient_path
+
+    print "INFO: Rpath fix applied. Verifying with otool:"
+    otool -l $eonclient_path | grep LC_RPATH -A 2
+}
```
Comment (danielnachun) [inline recipes/eon/build.nu]:
```suggestion
```
This fix should not be needed for the versions of macOS we use in CI.  Let's see how it works without it.

File: recipes/eon/variants.yaml [hunk 3]
```diff
@@ -0,0 +1,9 @@
+c_stdlib_version:
+  - if: osx and x86_64
+    then: '11.0'
+MACOSX_SDK_VERSION:
+  - if: osx and x86_64
+    then: '11.0'
+MACOSX_DEPLOYMENT_TARGET:
+  - if: osx and x86_64
+    then: '11.0'
```
Comment (danielnachun) [inline recipes/eon/variants.yaml]:
```suggestion
MACOSX_SDK_VERSION:
  - if: osx and x86_64
    then: '11.0'
```
`MACOSX_DEPLOYMENT_TARGET` is redundant with `c_stdlib`.  Furthermore, just setting `MACOSX_SDK_VERSION` is normally sufficient when `-D_LIBCPP_DISABLE_AVAILABILITY`.  Let's see what happens with the change suggested.

**Comment by HaoZeke** [comment]
@conda-forge/help-c-cpp, ready for review!

@danielnachun perhaps?

**Comment by HaoZeke** [comment]
@conda-forge/help-c-cpp, ready for review!


...

**Comment by danielnachun** [comment]
I made some changes to this:
- Switched to bash for `build.sh` - the commands we're running here are simple enough that there is no benefit to using something like nushell.  Furthermore, nushell seems to have considerable difficulty handling more complex environment variables like `${MESON_ARGS}` which is needed here.
- Proper assignment of build vs host dependencies

Please take a look before I merge it.

**Comment by HaoZeke** [comment]
> I made some changes to this:
> - Switched to bash for `build.sh` - the commands we're running here are simple enough that there is no benefit to using something like nushell.  Furthermore, nushell seems to have considerable difficulty handling more complex environment variables like `${MESON_ARGS}` which is needed here.
> - Proper assignment of build vs host dependencies
> 
> Please take a look before I merge it.

Thanks @danielnachun, looks good to me

**Comment by HaoZeke** [comment]
nudging @danielnachun

**Review by danielnachun — APPROVED** [review]
