### PR TITLE
Add r-coxme.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by cbrueffer** [comment]
@jdblischak any idea about this win64 error? I had 5 recipes fail with the same problem in short order, could this have something to do with the changes related to the R 3.3.2 removal?

**Comment by jdblischak** [comment]
@cbrueffer I'm not sure what is going on. The 3.3.2 removal shouldn't be the issue (that change won't be live until conda-forge switches to conda-build 3).

Interestingly, the [error](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.22230/job/x5wflywmli9etj2y#L1157) occurs when building for R 3.4.1, not 3.3.2. It fails during compilation. Do the other recipes that failed also require compilation?

```
Warning: R include directory is empty -- perhaps need to install R-devel.rpm or similar
make: C:/bld/r-coxme_1521058225176/_b_env/R/share/make/winshlib.mk: No such file or directory
make: *** No rule to make target 'C:/bld/r-coxme_1521058225176/_b_env/R/share/make/winshlib.mk'.  Stop.
Warning: running command 'make -f "C:/bld/r-coxme_1521058225176/_b_env/R/etc/x64/Makeconf" -f "C:/bld/r-coxme_1521058225176/_b_env/R/share/make/winshlib.mk" SHLIB="coxme.dll" WIN=64 TCLBIN=64 OBJECTS="agfit6b.o agfit6d.o bds_dsc.o bdsmatrix.o coxfit6a.o coxfit6b.o coxfit6c.o coxfit6d.o init.o"' had status 2
ERROR: compilation failed for package 'coxme'
* removing 'C:/bld/r-coxme_1521058225176/_b_env/R/library/coxme'
```

**Comment by cbrueffer** [comment]
You're right, it's only with 3.4.1. While this PR as well as https://github.com/conda-forge/staged-recipes/pull/5403 and https://github.com/conda-forge/staged-recipes/pull/5402 compile code, https://github.com/conda-forge/staged-recipes/pull/5401 and https://github.com/conda-forge/staged-recipes do not but fails with a similar message (as in, the package cannot be loaded).

**Comment by jdblischak** [comment]
Frustrating. Looks like timezones are causing a problem again.

```
Warning in as.POSIXlt.POSIXct(x, tz) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
Warning in as.POSIXlt.POSIXct(x, tz) : unknown timezone 'UTC'
Warning in as.POSIXlt.POSIXct(x, tz) : unknown timezone 'GMT'
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'America/New_York'
Warning in as.POSIXlt.POSIXct(x, tz) : unknown timezone 'GMT'
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'America/New_York'
```

There was lots of work on timezones in the recent 3.4.4 release ([NEWS](https://cran.r-project.org/doc/manuals/r-patched/NEWS.pdf)). Maybe we can backport a patch?

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17272
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17230
