### PR TITLE
Sfepy

### PR DESCRIPTION
**Pull request by wd15**
Recipe for [Sfepy](http://sfepy.org/doc-devel/index.html).

### CODE REVIEW

File: recipes/sfepy/meta.yaml [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+build:
+  number: 0
+  script: CFLAGS='-I${PREFIX}/include/python${CONDA_PY}m' python setup.py install --single-version-externally-managed --record record.txt
+  skip: true  # [win]
+
+requirements:
+  build:
+    - python
+    - anaconda
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Anaconda is too generic of a build (or run) requirement. Please narrow the list to the packages that are actually needed to run and build this library.

File: recipes/sfepy/meta.yaml [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    2D and 3D. It can be viewed both as black-box PDE solver, and as a
+    Python package which can be used for building custom
+    applications. The word simple means that complex FEM problems can
+    be coded very easily and rapidly.
+  doc_url: http://sfepy.org
+  dev_url: https://github.com/sfepy/sfepy
+
+extra:
+  recipe-maintainers:
+    - rc
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: @rc Are you ok with being listed as a co-maintainer on this conda-forge package?

File: recipes/sfepy/run_test.py [hunk 3]
```diff
@@ -0,0 +1 @@
+import sfepy
```
Comment (synapticarbors) [inline recipes/sfepy/run_test.py]: Please delete this file and just add a `test:import` section to the main recipe.

File: recipes/sfepy/meta.yaml [hunk 4]
```diff
@@ -0,0 +1,57 @@
+{% set rev = "d479f7a9" %}
+{% set name = "sfepy" %}
+{% set org = "sfepy" %}
+{% set version = "d479f7a9" %}
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: If possible, please use an actual version rather than a truncated git hash

File: recipes/sfepy/meta.yaml [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+
+package:
+  name: {{ name }}
+  version: {{ version }}
+
+source:
+  git_url: https://github.com/{{ org }}/{{ name }}.git
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Can we build this from an actual release?:

https://github.com/sfepy/sfepy/releases

File: recipes/sfepy/meta.yaml [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+  git_rev: {{ rev }}
+
+build:
+  number: 0
+  script: CFLAGS='-I${PREFIX}/include/python${CONDA_PY}m' python setup.py install --single-version-externally-managed --record record.txt
+  skip: true  # [win]
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: The `setup.py` seems to indicate that Windows is supported. Why are you skipping that build?

File: recipes/sfepy/meta.yaml [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+    - anaconda
+    - pyparsing
+    - sympy
+    - cython
+    - pytables
+    - mpi4py
+    - scikit-umfpack
+
+about:
+  home: http://{{ name }}.org
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Please just use the full explicit url so that it's easy to copy-and-paste if someone is inspecting the recipe and wants to go to the site.

File: recipes/sfepy/meta.yaml [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+  license: BSD-3-Clause
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Change to `BSD 3-clause`

File: recipes/sfepy/meta.yaml (hunk 2 above)
Comment (rc) [inline recipes/sfepy/meta.yaml]: Yes, please.

File: recipes/sfepy/meta.yaml (hunk 5 above)
Comment (rc) [inline recipes/sfepy/meta.yaml]: IMHO yes (not tested) - it should point to the same commit as the ``release_{{ version }}`` tag.

**Comment by synapticarbors** [comment]
A few notes:

- Please see the example `test` section to see how to do an import test and where it should go in the `meta.yaml` file:

https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L37-L42

- Please remove `anaconda` as a requirement and explicitly list the packages which are necessary to build and run `sfepy`.  Anaconda is a huge metapackage with many packages that are not needed to run this package. By only listing the minimal set of packages needed, we avoid unnecessary conflicts, keep the download size smaller, etc. Also make sure that packages listed in the `build` section are actually needed to build the recipe. If not, remove them.

**Comment by wd15** [comment]
@synapticarbors, sorry about the multiple pushes. I'm having issues with building the recipe and I was trying out different configurations against the CI systems. Both the issues you raised are fixed locally and I'll push them soon assuming I can build cleanly on my own system. Thanks.

**Comment by wd15** [comment]
Current issues:

 - This will likely fail on windows as `scikit-umfpack` is not available for windows. Scikit-umfpack is listed as a requirement for Sfepy, but it may be possible to use Sfepy without it. I need to investigate this, maybe @rc knows this.
 
 - The meta.yaml has requires an explicit path to the Python.h header files in 3.4, and 3.5, see https://github.com/wd15/staged-recipes/blob/sfepy/recipes/sfepy/meta.yaml#L16. The header files seem to be in `.../python3.5m` rather than `.../python3.5`. No idea why this is the case.

**Comment by wd15** [comment]
@rc, after removing scikit-umfpack as a dependency, the following error occurs on windows:

```
(root) C:\Miniconda\conda-bld\work>call activate.bat C:\Miniconda\envs\_build 
'CFLAGS' is not recognized as an internal or external command,
operable program or batch file.
Command failed: cmd.exe /c bld.bat
Command exited with code 1
```

See, https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.8544/job/uvq0nf1tteuum0ie#L467. 

I don't have access to windows to test this, do you regularly build sfepy on windows?

**Comment by rc** [comment]
@wd15 scikit-umfpack is not required - it just makes the tests involving a direct linear system solve slower (super-lu bundled with scipy is used in that case). As for the windows build error, neither I use  windows or regularly build on windows, but I will check the problem.

Currently, sfepy builds are tested only on linux using travis-ci on github. Having a windows CI setup and running would be good, but I would need help with that.

**Comment by wd15** [comment]
@rc, so the current status is that scikit-umfpack is no longer a dependency and is removed from meta.yaml, but we need help debugging the windows build.

**Comment by wd15** [comment]
The issue now is that we're setting the `CFLAGS` variable before `python setup.py ...` using

      script: CFLAGS='-I${PREFIX}/include/python3.5m -I${PREFIX}/include/python3.4m' python setup.py

Windows is not interpreting that in the same way as Linux. We need to set that because otherwise the build doesn't find the `Python.h` header. However, is there another way to set that without placing it in the `script` tag? I'm not sure how to set environment variables in the meta.yaml file.

**Comment by wd15** [comment]
The build was changed to use a separate `build.sh` for linux and `bld.bat` for windows. 5 out of 6 windows tests passed. The only failure was for

     Environment: TARGET_ARCH=x86, CONDA_PY=35, PY_CONDITION=python >=3.5, CONDA_INSTALL_LOCN=C:\Miniconda35

the error was

    - pytables -> numpy 1.10*|1.11*|1.6*|1.7*|1.8*
    - pytables -> python 2.6*|2.7*|3.3*|3.4*
    - python 3.5*
    Use "conda info <package>" to see the dependencies for each package.

which is strange because a test with a very similar environment

    Environment: TARGET_ARCH=x64, CONDA_PY=35, PY_CONDITION=python >=3.5, CONDA_INSTALL_LOCN=C:\Miniconda35-x64

seemed to pass just fine. What the difference between `Miniconda35-x64` and `Miniconda35`.

**Comment by rc** [comment]
@wd15 when I look at the failed build log, there is:

```
BUILD START: sfepy-2016.3-py35_0
    (actual version deferred until further download or env creation)
WARNING: conda-build appears to be out of date. You have version 1.21.14 but the
latest version is 2.0.7. Run
conda update -n root conda-build
to get the latest version.
...Traceback (most recent call last):
  File "C:\Miniconda35\lib\site-packages\conda_build_all\builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
AttributeError: module 'conda_build' has no attribute 'api'
During handling of the above exception, another exception occurred:
```

so cannot this be a conda problem?

**Comment by wd15** [comment]
@rc, I am not sure, but I don't think the AttributeError is significant. It seems to occur before another exception, when the subsequent exception is dealt with, the AttributeError goes away.

**Comment by rc** [comment]
@wd15 I see, thanks. On http://www.pytables.org/usersguide/installation.html there is a Python 3.5 info, so I guess the pytables conda recipe needs to be updated to work with Python 3.5 as well?

**Comment by wd15** [comment]
@rc, it seems that for most platforms that pytables is working just fine with Python 3.5. From the failure, it seems that pytables is unavailable for Python 3.5 on Windows x86, which is an edge case. I'm confused about whether this edge case is an absolute requirement to release on Conda-forge. I'm assuming that if Pytables is on Conda-forge and doesn't have that edge case satisfied, then Sfepy can also be on Conda-forge without that edge case satisfied. We may be misinterpreting the error message or using the wrong pytables recipe (is it pytables or tables for instance?). I would like to get some feedback from the conda-forge people on this. Could we amend our recipe to not use Windows x86 with Python 3.5?

**Comment by rc** [comment]
Yes, if that is the case, I would just leave that test out.

**Comment by rc** [comment]
@synapticarbors We think the PR is ready - could someone review?

File: recipes/sfepy/meta.yaml [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+    - mpi4py
+    - matplotlib
+
+  run:
+    - python
+    - numpy
+    - scipy
+    - pyparsing
+    - sympy
+    - cython
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Is cython required at runtime?

File: recipes/sfepy/meta.yaml [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+  git_rev: {{ rev }}
+
+build:
+  number: 0
+  skip: true  # [win]
+
+requirements:
+  build:
+    - python
+    - numpy
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: It was unclear to me glancing at the `setup.py` and src files, but I think this needs to be `numpy x.x` here and in the `run` section.

File: recipes/sfepy/meta.yaml [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+source:
+  git_url: https://github.com/{{ org }}/{{ name }}.git
+  git_rev: {{ rev }}
+
+build:
+  number: 0
+  skip: true  # [win]
+
+requirements:
+  build:
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: Are all of these packages required to build the recipe? I see a `package_check` function checking whether some of these are present, but many are marked as optional. If removing a library still allows the recipe to build, I would remove the ones that aren't explicitly required to build.

File: recipes/sfepy/meta.yaml [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+  name: {{ name }}
+  version: {{ version }}
+
+source:
+  git_url: https://github.com/{{ org }}/{{ name }}.git
+  git_rev: {{ rev }}
+
+build:
+  number: 0
+  skip: true  # [win]
```
Comment (synapticarbors) [inline recipes/sfepy/meta.yaml]: There is now a `bld.bat`, but you're skipping the windows build.

File: recipes/sfepy/meta.yaml (hunk 9 above)
Comment (rc) [inline recipes/sfepy/meta.yaml]: @synapticarbors Thanks for looking at the recipe. I think this would do:

```
requirements:
  build:
    - python
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy
    - pyparsing
    - sympy
    - pytables
    - mpi4py
    - matplotlib
```

@wd15 Could you try the above changes?

As for skipping the windows build, we did not find how to disable only Windows x86 with Python 3.5 (IIRC), see above: "it seems that pytables is unavailable for Python 3.5 on Windows x86," - this configuration failed, saying that requirements for pytables could not be satisfied, while other windows configurations (e.g. Python 3.4) were OK.

**Comment by jakirkham** [comment]
> From the failure, it seems that pytables is unavailable for Python 3.5 on Windows x86...

Are you sure? I'm seeing Python 3.5 32-bit binaries for Windows on conda-forge. 😕 Could you please double check that this is the error and not something else?

**Comment by rc** [comment]
The error for 

```
 Environment: TARGET_ARCH=x86, CONDA_PY=35, PY_CONDITION=python >=3.5, CONDA_INSTALL_LOCN=C:\Miniconda35
```

reported by appveyor was:

```
- pytables -> numpy 1.10*|1.11*|1.6*|1.7*|1.8*
- pytables -> python 2.6*|2.7*|3.3*|3.4*
- python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

Other windows builds succeeded. We did not see other problems in the appveyor output. Anyway, we can re-enable it and see.

**Comment by rc** [comment]
@wd15 thanks! It looks that the windows build passes now... :)

**Comment by wd15** [comment]
@synapticarbors, @jakirkham: it looks like this is ready to merge now

 - all the tests pass on all the platforms
 - unnecessary packages are removed from the  build section
 - the `numpy x.x` directive is added and resolves some test failures

**Comment by wd15** [comment]
Going to close this and reopen a new pull request to see if it that prompts it to be included in conda-forge.
