### PR TITLE
add ctransformers

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by raybellwaves** [comment]
```
  --------------------------------------------------------------------------------
  -- Trying 'Unix Makefiles' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.

  Not searching for unused variables given on the command line.

  CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Unix Makefiles' generator - failure

```

**Comment by raybellwaves** [comment]
```  ModuleNotFoundError: No module named 'skbuild'
  error: subprocess-exited-with-error
```

**Comment by raybellwaves** [comment]
scikit-build is in build. dupping to host

**Comment by raybellwaves** [comment]
Interesting only windows works

Mac fails (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/871781/logs/24) at

```
2024-02-06T13:53:40.3721760Z   13 warnings generated.
2024-02-06T13:53:40.4083100Z   [ 33%] Building C object CMakeFiles/ctransformers.dir/models/ggml/ggml.c.o
2024-02-06T13:53:41.6311300Z   /Users/runner/Miniforge3/conda-bld/ctransformers_1707227330441/work/models/ggml/ggml.c:540:5: error: call to undeclared function 'clock_gettime'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-02-06T13:53:41.6312140Z       clock_gettime(CLOCK_MONOTONIC, &ts);
2024-02-06T13:53:41.6312460Z       ^
2024-02-06T13:53:41.6363990Z   /Users/runner/Miniforge3/conda-bld/ctransformers_1707227330441/work/models/ggml/ggml.c:540:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
2024-02-06T13:53:41.6366630Z       clock_gettime(CLOCK_MONOTONIC, &ts);
2024-02-06T13:53:41.6368620Z                     ^
2024-02-06T13:53:41.6369970Z   /Users/runner/Miniforge3/conda-bld/ctransformers_1707227330441/work/models/ggml/ggml.c:546:5: error: call to undeclared function 'clock_gettime'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-02-06T13:53:41.6372410Z       clock_gettime(CLOCK_MONOTONIC, &ts);
2024-02-06T13:53:41.6373140Z       ^
2024-02-06T13:53:41.6417530Z   /Users/runner/Miniforge3/conda-bld/ctransformers_1707227330441/work/models/ggml/ggml.c:546:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
```

Linux (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/871781/logs/18) fails at  `Trying 'Unix Makefiles' generator - failure`

**Comment by raybellwaves** [comment]
Builds ok on my mac using

`/Users/ray/miniforge3/envs/main/conda-bld/ctransformers_1707237890054/work/_skbuild/macosx-10.9-x86_64-3.10/cmake-build`

I see conda-forge is using 3.11 /Users/runner/Miniforge3/conda-bld/ctransformers_1707227330441/work/_skbuild/macosx-10.9-x86_64-3.11/cmake-build

**Comment by raybellwaves** [comment]
@conda-forge-admin please rerender

**Comment by raybellwaves** [comment]
Using 3.10 didn't fix the max issue

**Comment by raybellwaves** [comment]
Currently the pipeline has The C compiler identification is Clang 16.0.6. Works on my mac with Clang 17.0.6

**Comment by raybellwaves** [comment]
Green! Good night!

**Comment by raybellwaves** [comment]
@conda-forge/staged-recipes this one is ready for review.

**Comment by raybellwaves** [comment]
@conda-forge/help-python-c this one is ready for review.
