### PR TITLE
Add feather-format recipe

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
feather/feather-format does not look to support Windows yet, wesm/feather#111, so no Windows build is attempted.

**Comment by jjhelmus** [comment]
Anyone else interesting in being a maintainer on this recipe.  Feather is a fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow.

**Comment by msarahan** [comment]
Sure, I'm happy to help out.

**Comment by jreback** [comment]
prob want to ping 
cc @wesm

File: recipes/feather-format/build.sh [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#!/bin/bash
+
+if [ "$(uname)" == "Darwin" ]; then
+    # Building Feather requires a C++11 compiler, which requires OS X 10.9+
+    export MACOSX_DEPLOYMENT_TARGET=10.9
```
Comment (jakirkham) [inline recipes/feather-format/build.sh]: Could we please try setting this to 10.7? That should work.

Comment (jreback) [inline recipes/feather-format/build.sh]: https://github.com/wesm/feather/tree/master/python recommends setting to 10.10 actually.

Comment (jjhelmus) [inline recipes/feather-format/build.sh]: 10.10 seems very restrictive.  I used 10.9 when I built the feather-format 0.1 package in my channel and have not received any emails about it not working.  

I submitted a build using 10.7, lets see if that works.  From what I recall, 10.9 was the earliest I could set the target and have the package build, but my memory of that is a bit hazy and I may have been missing the correct SDKs on my machine.

**Comment by jjhelmus** [comment]
The package does not compile when the MACOSX_DEPLOYMENT_TARGET is set to 10.7

```
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Ifeather -I/Users/travis/miniconda/envs/_build/lib/python2.7/site-packages/numpy/core/include -I/Users/travis/miniconda/conda-bld/work/feather-format-0.2.0/src -I/Users/travis/miniconda/envs/_build/include/python2.7 -c feather/ext.cpp -o build/temp.macosx-10.5-x86_64-2.7/feather/ext.o -std=c++11 -O3
In file included from feather/ext.cpp:307:
In file included from /Users/travis/miniconda/conda-bld/work/feather-format-0.2.0/src/feather/api.h:18:
/Users/travis/miniconda/conda-bld/work/feather-format-0.2.0/src/feather/buffer.h:19:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/staged-recipes/recipes/feather-format/build.sh
```

Trying 10.8...

**Comment by jakirkham** [comment]
Alright, let me give it a try.

**Comment by jjhelmus** [comment]
Same issue with 10.8.  

`cstdint.h` can be found in /usr/include/c++/4.2.1/tr1 and including that directory in the build_ext step successfully builds the extension, e.g. `$PYTHON setup.py build build_ext -n -I/usr/include/c++/4.2.1/tr1` I cannot figure out how to get the install step to recognize that the extension has already been built.  Everything I try either rebuilds the extension and fails with the missing cstdint or clobbers the build directory and includes the ext.pyx file rather than the compiled module.  Anyone have more experience with distutils/setuptools and how the build and install commands interact?

**Comment by jakirkham** [comment]
Yeah, I'm seeing that error. Am trying to play with it.

**Comment by jakirkham** [comment]
Alright I have a fix. PR incoming.

**Comment by jjhelmus** [comment]
> Alright I have a fix. PR incoming.

Great!

**Comment by jakirkham** [comment]
See this PR ( https://github.com/jjhelmus/staged-recipes/pull/1 ).

**Comment by jjhelmus** [comment]
Works for me locally, thanks for the fix @jakirkham

File: recipes/feather-format/build.sh [hunk 2]
```diff
@@ -0,0 +1,9 @@
+#!/bin/bash
+
+if [ "$(uname)" == "Darwin" ]; then
+    export MACOSX_DEPLOYMENT_TARGET=10.7
+    export CFLAGS="${CXXFLAGS} -stdlib=libc++ -std=c++11"
```
Comment (jakirkham) [inline recipes/feather-format/build.sh]: It's pretty weird putting this stuff in `CFLAGS`, but it seemed to ignore it otherwise. If someone has some better ideas here, that would be great. Maybe `feather-format` needs to be using `CXXFLAGS` or it calls it something else (`CPPFLAGS`?).

**Comment by jakirkham** [comment]
> Works for me locally, thanks for the fix @jakirkham

Sure, glad to help.

File: recipes/feather-format/meta.yaml [hunk 3]
```diff
@@ -0,0 +1,36 @@
+package:
+  name: feather-format
+  version: "0.2.0"
+
+source:
+  fn: feather-format-0.2.0.tar.gz
+  url: https://pypi.python.org/packages/06/bb/072a00246f235df6a902dbaf4cb10d687ea5b3a199f786dd99c23cd08cf8/feather-format-0.2.0.tar.gz
```
Comment (jakirkham) [inline recipes/feather-format/meta.yaml]: Can be changed to this [https://pypi.io/packages/source/f/feather-format/feather-format-0.2.0.tar.gz]( https://pypi.io/packages/source/f/feather-format/feather-format-0.2.0.tar.gz ). Sorry it is a pane. Blame PyPI for the mess.

With that done, could use jinja for the versions if you like. Might make things easier down the road.

Comment (jakirkham) [inline recipes/feather-format/meta.yaml]: Sorry, probably should have included that in the PR. I was more focused on getting it building quickly.

**Comment by jakirkham** [comment]
LGTM

**Comment by jakirkham** [comment]
Thanks @jjhelmus.

File: recipes/feather-format/build.sh [hunk 4]
```diff
@@ -0,0 +1,9 @@
+#!/bin/bash
+
+if [ "$(uname)" == "Darwin" ]; then
+    export MACOSX_DEPLOYMENT_TARGET=10.7
```
Comment (wesm) [inline recipes/feather-format/build.sh]: If 10.7 is the earliest deployment target supporting C++11 we should update the docs in the Feather repo too
