### PR TITLE
add ledger

### PR DESCRIPTION
**Pull request by twrightsman**
Checklist

- [x] License file is packaged
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by twrightsman** [comment]
@conda-forge/help-c-cpp

**Comment by twrightsman** [comment]
Not sure why the Linux and Mac builds are being skipped. Could someone check this?

File: recipes/ledger/meta.yaml [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+  name: {{ name|lower }}
+  version: {{ version }}
+
+source:
+  url: https://github.com/ledger/ledger/archive/v{{ version }}.tar.gz
+  sha256: b248c91d65c7a101b9d6226025f2b4bf3dabe94c0c49ab6d51ce84a22a39622b
+
+build:
+  number: 0
+  skip: True  # [not (py<=27 and unix)]
```
Comment (dbast) [inline recipes/ledger/meta.yaml]: The python version is already specified via the requirements, so this can be simplified to:
```suggestion
  skip: True  # [win]
```

**Comment by twrightsman** [comment]
Hmm, I'm not sure about the C++ compilation errors. I believe ledger tests against boost 1.61 and fails on the latest boost. Is it possible to use that boost version even though conda-forge has 1.70 pinned? Alternatively there may some straightforward fixes to the code to port from 1.61 to 1.70?

**Comment by twrightsman** [comment]
Seems fixed in unreleased https://github.com/ledger/ledger/pull/1817 but unsure if master builds against latest boost. I will try to build with master.

File: recipes/ledger/meta.yaml [hunk 2]
```diff
@@ -0,0 +1,63 @@
+{% set name = "ledger" %}
+{% set version = "3.1.3dev16" %}
```
Comment (scopatz) [inline recipes/ledger/meta.yaml]: We generally don't build dev packages due to CI limits.  Is there a full release that is available?

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: @scopatz The latest full release doesn't build with conda-forge's pinned boost versions. I was hoping to have this dev build until I ask the devs to create a new release with my fixes (https://github.com/ledger/ledger/pull/1823) to build with boost 1.70.

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: To be clear, I would update this pull request once I get the fixes merged to build a new dev version and then try to get a new release created that can be built with conda-forge. Let me know if you'd rather leave this pull request open until the full release is available, but I'm unsure on how long this will take.

Comment (scopatz) [reply recipes/ledger/meta.yaml]: I think I'd prefer to wait, but someone else on @conda-forge/staged-recipes might be more open to it.

Comment (isuruf) [reply recipes/ledger/meta.yaml]: @twrightsman, you can build the release but add your PR as a patch. See https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#patches

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: @isuruf That looks like a great solution, I'll give it a shot

Comment (isuruf) [reply recipes/ledger/meta.yaml]: @twrightsman, can you only use the diff from ledger/ledger#1823 and remove other changes in the dev17.patch?

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: Okay, I'll add another commit

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: @isuruf dev17.patch may contain fixes besides mine since v3.1.3 that are required for proper building, but we can try it

**Comment by twrightsman** [comment]
macOS can be skipped for now since homebrew provides ledger

File: recipes/ledger/meta.yaml (hunk 2 above)
Comment (twrightsman) [reply recipes/ledger/meta.yaml]: I'll need to cherry-pick the master commits to avoid feature changes and include any required build changes, will update the patch file when I find a minimal working set

**Comment by twrightsman** [comment]
@scopatz @isuruf @dbast I think we are ready to merge if there are no additional objections?

File: recipes/ledger/meta.yaml [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    - gmp >=4.2.2
+    - mpfr >=2.4.0
+    - utfcpp >=2.3.4
+    - gettext >=0.17 # optional
+    - libedit >=3.0.200901011 # optional
+    - python >=2.4,<3 # optional
+
+test:
+  commands:
+    ledger | grep {{ version }}
```
Comment (isuruf) [inline recipes/ledger/meta.yaml]:
```suggestion
    - ledger | grep {{ version }}
```

File: recipes/ledger/meta.yaml [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+build:
+  number: 0
+  skip: True  # [win or osx]
+
+requirements:
+  build:
+    - {{ compiler('cxx') }}
+    - cmake
+    - make
+    - python >=2.4,<3
```
Comment (isuruf) [inline recipes/ledger/meta.yaml]: Remove this

File: recipes/ledger/meta.yaml [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+  host:
+    - boost >=1.49
```
Comment (isuruf) [inline recipes/ledger/meta.yaml]: You need to remove the versions here for conda-build to use the global values from `conda_build_config.yaml`.

File: recipes/ledger/meta.yaml (hunk 4 above)
Comment (twrightsman) [reply recipes/ledger/meta.yaml]: Remove all four lines? Are these by default included in the build environment? As for Python, the build requires the Python 2.7 libraries

Comment (isuruf) [reply recipes/ledger/meta.yaml]: No, one line. `python` should be in host and yes, python version should be skipped using a selector. See for eg: https://github.com/conda-forge/numpy-feedstock/blob/master/recipe/meta.yaml

File: recipes/ledger/build.sh [hunk 6]
```diff
@@ -0,0 +1,9 @@
+#!/bin/sh
+set -ex
+
+cmake . \
+  -DUSE_PYTHON=ON \
+  -DCMAKE_INSTALL_PREFIX="${PREFIX}"
```
Comment (isuruf) [inline recipes/ledger/build.sh]: add `-DCMAKE_INSTALL_LIBDIR=lib` here.

File: recipes/ledger/meta.yaml [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+source:
+  url: https://github.com/ledger/ledger/archive/v{{ version }}.tar.gz
+  sha256: {{ sha256 }}
+  patches:
+    - fix-build.patch
+
+build:
+  number: 0
+  skip: True  # [win or osx or py>27]
```
Comment (isuruf) [inline recipes/ledger/meta.yaml]: Add,
```yaml
  run_exports:
    - {{ pin_subpackage("ledger") }}
```

File: recipes/ledger/build.sh (hunk 6 above)
Comment (twrightsman) [reply recipes/ledger/build.sh]: Could you explain this suggestion?

File: recipes/ledger/meta.yaml (hunk 7 above)
Comment (twrightsman) [reply recipes/ledger/meta.yaml]: Could you also explain this suggestion a little further?

File: recipes/ledger/build.sh (hunk 6 above)
Comment (isuruf) [reply recipes/ledger/build.sh]: this will install the libraries to `${PREFIX}/lib` instead of `${PREFIX}/lib64`

File: recipes/ledger/meta.yaml (hunk 7 above)
Comment (isuruf) [reply recipes/ledger/meta.yaml]: When a downstream library links to this library, this will add a version constraint for `ledger` in the downstream library so that the major version is pinned. This is to ensure that downstream packages linking to `libledger.so.3` will always use the major version 3

File: recipes/ledger/meta.yaml [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+  run_exports:
+    - {{ pin_subpackage("ledger") }}
+
+requirements:
+  build:
+    - {{ compiler('cxx') }}
+    - cmake
+    - make
+    - python
```
Comment (isuruf) [inline recipes/ledger/meta.yaml]: You need to remove this here as `python` should be in host.

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: Even if ledger requires the Python dev libraries to build?

Comment (isuruf) [reply recipes/ledger/meta.yaml]: Yes, please read https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build

Comment (twrightsman) [reply recipes/ledger/meta.yaml]: Thanks for linking that, it makes sense now; commit pushed

**Comment by scopatz** [comment]
LGTM
