### PR TITLE
adding hs-process recipe

### PR DESCRIPTION
**Pull request by tnigon**
This is my first time contributing to conda-forge, so excuse my ignorance (I do want to learn). Two things I had troubles with when doing the `conda build -c conda-forge hs-process` command:
1) tests: I do have test files in my PyPI package (hs-process/tests/test.py), but I could not for the life of me figure out how to run this test from the meta.yaml file, so I left it out altogether. I tried copying these test files into this recipe, but to no avail. Tried also renaming test.py to run_test.py, but still didn't work. If you know, please let me know how to get my tests to run properly with `conda build`.
2) dependencies: after a successful `conda build`, I installed the newly built tar.bz2 file locally, but no dependencies were installed. After reading many forums/issue trackers, I believe this is normal behavior. I do want to be sure all the dependencies are installed for a user installing via conda-forge, so this is important for me. I think I may just have to be patient and it will work itself out, but again, if I should be doing something different, any help is appreciated.

test.py does succeed when installing dependencies manually, then installing my package locally via the newly built tar.bz2, so I'm hopeful everything is working properly.

Thanks for your patience, I'm trying to learn the best I can. Thanks!

Tyler

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by tnigon** [comment]
I am good being the maintainer. Also, what I should do to get appveyor build to pass. I'll research this now..

File: recipes/hs-process/meta.yaml [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  name: "{{ name|lower }}"
+  version: "{{ version }}"
+
+source:
+  url: "https://files.pythonhosted.org/packages/bb/12/820c4894f45ebeb6338e9fa8c6f070aa5b869b97c4a1fefb04bd70f8417c/hs_process-0.0.3.tar.gz"
+  sha256: ec8adc1562e5d7175341f3a58a0e08fd3f72915fa6a2eba12c841aaf5397cf65
+
+build:
+  number: 0
+  script: "{{ PYTHON }} -m pip install . -vv"
```
Comment (scopatz) [inline recipes/hs-process/meta.yaml]: Can this be noarch python?

File: recipes/hs-process/meta.yaml [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+requirements:
+  host:
+    - pip
+    - python ==3.7
```
Comment (scopatz) [inline recipes/hs-process/meta.yaml]: Does this really only work with python 3.7?

**Comment by scopatz** [comment]
Appveyor doesn't need to pass if azure does

File: recipes/hs-process/meta.yaml (hunk 1 above)
Comment (tnigon) [reply recipes/hs-process/meta.yaml]: I don't know anything about noarch python. So maybe - where can I find out more or do some tests to find out?

File: recipes/hs-process/meta.yaml (hunk 2 above)
Comment (tnigon) [reply recipes/hs-process/meta.yaml]: Python 3.7 is all I've worked on. I do know it does not work on python 3.8, I think due to the goepandas/GDAL dependencies. I'm guessing it will work on other version of python 3 - can this be determined by just changing the meta.yaml file?

Comment (tnigon) [reply recipes/hs-process/meta.yaml]: Just installed and tested with python 2.7, 3.5, 3.6, and 3.7
2.7: passes 16/19 tests (issues with copying a list "'list' object has no attribute 'copy'")
3.5: passes 18/19 tests (issues with converting Series to numpy "'Series' object has no attribute 'to_numpy'")
3.6: passes 19/19 tests

Note that the tests are pretty basic at this point.
3.7: passes 19/19 tests

**Comment by tnigon** [comment]
After removing the python ==3.7 restriction from meta.yaml, conda-build works fine on my local machine (Windows 10), but I see it is failing here for (win_64). Not sure how to proceed, so I appreciate any advice. Thanks!

File: recipes/hs-process/meta.yaml [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+  name: "{{ name|lower }}"
+  version: "{{ version }}"
+
+source:
+  url: "https://files.pythonhosted.org/packages/bb/12/820c4894f45ebeb6338e9fa8c6f070aa5b869b97c4a1fefb04bd70f8417c/hs_process-0.0.3.tar.gz"
+  sha256: ec8adc1562e5d7175341f3a58a0e08fd3f72915fa6a2eba12c841aaf5397cf65
+
+build:
+  number: 0
+  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
```
Comment (scopatz) [inline recipes/hs-process/meta.yaml]: Please add `noarch: python` here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages

Comment (tnigon) [reply recipes/hs-process/meta.yaml]: @scopatz Done, and looks like they are passing now.

**Comment by scopatz** [comment]
Thanks!
