### PR TITLE
re2 package

### PR DESCRIPTION
**Pull request by scopatz**
For google's regular expression library

### CODE REVIEW

**Comment by scopatz** [comment]
@conda-forge/core, any idea why this is trying to build for multiple versions of Python, even though Python is not available. Also, any idea as to why Windows can build with a VC14 feature but then fail to install?

**Comment by scopatz** [comment]
@jakirkham @ocefpaf @pelson, any idea what is going on here?

**Comment by scopatz** [comment]
Any ideas?

**Comment by jakirkham** [comment]
Maybe add some `pwd` and `ls` statements. That is very odd.

Unfortunately I don't have time near term to sink into this. Sorry about that.

**Comment by scopatz** [comment]
Well, I am more interested in how to restrict the build to just VC 14 and not be dependent on the Python version. Is there any docs you can point me to on that, please?  I am happy to debug, but it seems like conda forge is doing things I wouldn't expect

**Comment by scopatz** [comment]
For example, Why is conda-build on v1.21.  This seems super out of date...


```
WARNING: conda-build appears to be out of date. You have version 1.21.14 but the
latest version is 2.0.8. Run
conda update -n root conda-build
to get the latest version.
...Traceback (most recent call last):
  File "C:\Miniconda35\lib\site-packages\conda_build_all\builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
AttributeError: module 'conda_build' has no attribute 'api'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda35\Scripts\conda-build-all-script.py", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda35\lib\site-packages\conda_build_all\cli.py", line 90, in main
    b.main()
  File "C:\Miniconda35\lib\site-packages\conda_build_all\builder.py", line 263, in main
    built_dist_location = self.build(meta, build_config)
  File "C:\Miniconda35\lib\site-packages\conda_build_all\builder.py", line 204, in build
    return bldpkg_path(build.build(meta.meta))
  File "C:\Miniconda35\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Miniconda35\lib\site-packages\conda_build_all\version_matrix.py", line 376, in setup_vn_mtx_case
    yield
  File "C:\Miniconda35\lib\site-packages\conda_build_all\builder.py", line 204, in build
    return bldpkg_path(build.build(meta.meta))
  File "C:\Miniconda35\lib\site-packages\conda_build_all\build.py", line 36, in build
    build_module.test(meta, **kwd)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 770, in test
    create_env(config.test_prefix, specs, debug=debug)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 395, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "C:\Miniconda35\lib\site-packages\conda\plan.py", line 469, in install_actions
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\Miniconda35\lib\site-packages\conda\resolve.py", line 944, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda35\lib\site-packages\conda\resolve.py", line 981, in solve
    dists, new_specs = self.get_dists(specs)
  File "C:\Miniconda35\lib\site-packages\conda\resolve.py", line 592, in get_dists
    raise Unsatisfiable(save_unsat)
conda.resolve.Unsatisfiable: The following specifications were found to be in conflict:
  - re2 2016.11.01 vc14_0 -> feature:vc14
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by isuruf** [comment]
@scopatz I had the same questions and here are some answers,

Building multiple times,
https://github.com/conda-forge/staged-recipes/pull/211#r57540626

MSVC14 and Python
https://github.com/conda-forge/staged-recipes/pull/211#issuecomment-202209196

**Comment by isuruf** [comment]
There is a file named `BUILD` in the source, https://github.com/google/re2/blob/master/BUILD and I'm guessing Mac OSX is case insensitive.

**Comment by jakirkham** [comment]
> There is a file named `BUILD` in the source, https://github.com/google/re2/blob/master/BUILD and I'm guessing Mac OSX is case insensitive.

Good point. Did not know that was there. Not always, but yes the most common format for a partition on OS X is case insensitive.

**Comment by jakirkham** [comment]
> Why is conda-build on v1.21

Because `cmake` doesn't work on `conda-build` version 2.

xref: https://github.com/conda-forge/cmake-feedstock/issues/21

**Comment by scopatz** [comment]
Wow, great find with the BUILD dir there @isuruf! Thanks!  

On the VC version stuff.  I had added that, and it was still failing. It seems peculiar that non-Python packages would depend on the Python version at all.

Also, I think it is really past time to have some documentation on this stuff. I never would have found those comment in that issue.  I am happy to start capturing this stuff somewhere.  

@jakirkham et @conda-forge/core is there any place that we could put sphinx source that gets uploaded to conda-forge.github.io?  I'd be happy to set it up. What is in the wiki isn't enough, I don't think.

**Comment by jakirkham** [comment]
> is there any place that we could put sphinx source that gets uploaded to conda-forge.github.io? I'd be happy to set it up. What is in the wiki isn't enough, I don't think.

Go for it! 👍

Set up some guidelines in this [`docs` directory]( https://github.com/conda-forge/conda-forge.github.io/tree/master/docs ). Feel free to add whatever you wish and structure it as you see fit. It gets generated on [RTD]( http://conda-forge.readthedocs.io/en/latest/ ).

**Comment by scopatz** [comment]
Ok I think that I have gotten past the VC 14 issues.  However, I am not sure what is going on with the failure to activate the test env on windows.  Is that something that we know about?

```
TEST START: re2-2016.11.01-0
WARNING: conda-build appears to be out of date. You have version 1.21.14 but the
latest version is 2.0.8. Run
conda update -n root conda-build
to get the latest version.
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    re2-2016.11.01             |                0         183 KB  local
The following NEW packages will be INSTALLED:
    re2: 2016.11.01-0 local
(root) C:\Miniconda35\conda-bld\test-tmp_dir>call activate.bat C:\Miniconda35\envs\_test 
TESTS FAILED: re2-2016.11.01-0
Command exited with code 1
```

**Comment by isuruf** [comment]
That's not a failure to activate the test env. Tests actually failed, but it doesn't say that.

File: recipes/re2/bld.bat [hunk 1]
```diff
@@ -0,0 +1,17 @@
+mkdir -p build
+cd build
+cmake -DBUILD_SHARED_LIBS=ON ^
+      -DCMAKE_BUILD_TYPE=Release ^
+      -DCMAKE_INSTALL_PREFIX=%PREFIX% ^
```
Comment (isuruf) [inline recipes/re2/bld.bat]: Use `%LIBRARY_PREFIX%` as that is what you are checking in meta.yaml

File: recipes/re2/build.sh [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+builddir="${SRC_DIR}/cmake-build"
+mkdir -p ${builddir}
+cd ${builddir}
+cmake -DBUILD_SHARED_LIBS=ON \
+      -DCMAKE_BUILD_TYPE=Release \
+      -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+      -DCMAKE_OSX_DEPLOYMENT_TARGET="${MACOSX_VERSION_MIN}" \
+      "${SRC_DIR}"
+make -j "${CPU_COUNT}"
+make -j "${CPU_COUNT}" test
```
Comment (isuruf) [inline recipes/re2/build.sh]: ctest can be used to run tests and it can skip tests.
`ctest -E "dfa|exhaustive|random"` would skip the tests in your patch and you don't need the patch

File: recipes/re2/meta.yaml [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+  #  - vc9     # [win and py27]
+  #  - vc10    # [win and py34]
+  #  - vc14    # [win and py35]
+  detect_binary_files_with_prefix: True
+  #msvc_compiler: 14.0
+
+requirements:
+  build:
+    - toolchain
+    - cmake >=3.1
```
Comment (isuruf) [inline recipes/re2/meta.yaml]: Needs `cmake >= 3.4` for windows

File: recipes/re2/meta.yaml [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+test:
+  commands:
+    - test -f ${PREFIX}/lib/libre2.so  # [linux]
+    - test -f ${PREFIX}/lib/libre2.dylib  # [osx]
+    - test -f ${PREFIX}/include/re2/re2.h  # [unix]
+    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1  # [win]
+    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1  # [win]
```
Comment (isuruf) [inline recipes/re2/meta.yaml]: You need the dll because it is a shared build, but it is not getting installed, try the following patch
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3c90f5d..01bdc72 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -128,4 +128,5 @@ set(RE2_HEADERS
     )
 
 install(FILES ${RE2_HEADERS} DESTINATION include/re2)
-install(TARGETS re2 ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
+install(TARGETS re2 ARCHIVE DESTINATION lib LIBRARY DESTINATION lib
+                    RUNTIME DESTINATION bin)
```

File: recipes/re2/bld.bat [hunk 5]
```diff
@@ -0,0 +1,17 @@
+mkdir -p build
```
Comment (isuruf) [inline recipes/re2/bld.bat]: In appveyor this gives an error, but doesn't fail the build. It's better to use another name here.

File: recipes/re2/meta.yaml (hunk 3 above)
Comment (scopatz) [inline recipes/re2/meta.yaml]: I am clearly a windows novice :)

Comment (isuruf) [inline recipes/re2/meta.yaml]: FYI, CMake >= 3.4 is needed for this feature, https://github.com/google/re2/blob/master/CMakeLists.txt#L23

**Comment by scopatz** [comment]
Hey @isuruf, thanks so much for all of this help so far.  I'd happily add you as a maintainer if you are interested...

**Comment by isuruf** [comment]
This doesn't have `vs2015_runtime` as a runtime requirement. Why is that?

**Comment by scopatz** [comment]
I don't think it needs it, It just needs >VC13

**Comment by scopatz** [comment]
Finally seems to pass!

**Comment by isuruf** [comment]
'd be happy to help with maintaining.
Let's wait for somebody to comment on the VS issue. Otherwise looks good.

**Comment by scopatz** [comment]
Great, @isuruf! I have added you.  Who can we ask about the VS part?

**Comment by isuruf** [comment]
Found an old comment here, https://github.com/conda-forge/mpfr-feedstock/pull/3#r65817883

Since you are compiling in a Python3.5 environment, it is using MSVC 2015 and therefore needs `msvc2015_runtime` as a runtime dependency. So best way to add this is to add,

```
- vc 14   # [win]
```
as build time and runtime dependency.

Note that MSVC 2013 is not supported by conda-forge as conda-forge is only using the MSVC runtimes related to Python versions.

File: recipes/re2/meta.yaml [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+package:
+  name: {{ name|lower }}
+  version: {{ version }}
+
+source:
+  fn: {{ name }}-{{ version }}.tar.gz
+  url: http://github.com/google/{{ name }}/archive/{{ dashversion }}.tar.gz
+  sha256: {{ sha256 }}
+  patches:
+    - win-cmakelists.patch  # [win]
```
Comment (jakirkham) [inline recipes/re2/meta.yaml]: Please raise an issue and/or open a PR upstream explaining the problem and the need for this sort of change.

Comment (isuruf) [inline recipes/re2/meta.yaml]: Done. google/re2#123

**Comment by jakirkham** [comment]
Thanks @scopatz and @isuruf .

File: recipes/re2/meta.yaml [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+
+build:
+  number: 0
+  skip: True  # [not py35]
```
Comment (jakirkham) [inline recipes/re2/meta.yaml]: Apparently missed this. 😔

It is causing all builds to be skipped in the feedstock. Please remove this `skip` and re-render in a fresh PR from your fork.

File: recipes/re2/meta.yaml (hunk 6 above)
Comment (scopatz) [inline recipes/re2/meta.yaml]: Thanks @isuruf

File: recipes/re2/meta.yaml (hunk 7 above)
Comment (scopatz) [inline recipes/re2/meta.yaml]: Happy to do this @jakirkham! But I don't understand how this is the trigger.  I see that no artefacts are being collected...  https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.8952/job/den9lm6ivvne8em4

Comment (isuruf) [inline recipes/re2/meta.yaml]: Issue is that builds are skipped when python!=3.5, but there is no python in build requirements, so conda-smithy will not generate ci yaml files.

Comment (scopatz) [inline recipes/re2/meta.yaml]: But `conda build` clearly runs and builds the package.  What am I missing?

Comment (isuruf) [inline recipes/re2/meta.yaml]: `conda build` runs it on this repo. Issue is that conda-smithy thinks you are skipping the build.

Comment (scopatz) [inline recipes/re2/meta.yaml]: Oh OK.  I guess I don't really understand how conda-smithy works then.  The whole VC system interacting with python versions seems strange, though.

Comment (isuruf) [inline recipes/re2/meta.yaml]: Yes, but that's a different issue though.

Comment (jakirkham) [inline recipes/re2/meta.yaml]: So `conda-build-all` is used in `staged-recipes` and it runs using [matrix conditions]( https://github.com/conda-forge/staged-recipes/blob/fa6d6c913cc49982cd39d9601162315f88e144ce/appveyor.yml#L99 ) that effectively force a range of `python` versions to be tried anyways.

While the feedstocks have the same [matrix conditions]( https://github.com/conda-forge/conda-smithy/blob/4f10b7d47b08b9e98b216be2d31bfe3d14673fb7/conda_smithy/configure_feedstock.py#L405 ) used by `conda-build-all` to inform `conda-smithy`, they are used to determine what [actually cases]( https://github.com/conda-forge/conda-smithy/blob/4f10b7d47b08b9e98b216be2d31bfe3d14673fb7/conda_smithy/configure_feedstock.py#L279-L280 ) will really be built for to [fill out the template]( https://github.com/conda-forge/conda-smithy/blob/4f10b7d47b08b9e98b216be2d31bfe3d14673fb7/conda_smithy/configure_feedstock.py#L322-L324 ). As there never was a Python 3.5 case, we find the CI is [dropped]( https://github.com/conda-forge/conda-smithy/blob/4f10b7d47b08b9e98b216be2d31bfe3d14673fb7/conda_smithy/configure_feedstock.py#L289-L293 ).

Comment (jakirkham) [inline recipes/re2/meta.yaml]: Hope that explanation helps. 😄
